### ISSUE TITLE
没找到monitor的数据库文件

### ISSUE THREAD

**Issue by q6990774** [flywithbug-vue-admin/vue-admin#1]
刚刚接触，没找到mongo的monitor库文件，报了空指针异常

**Comment by flywithbug** [comment]
我把项目拆分了下，https://github.com/flywithbug-vue-admin/go-eladmin  这里是后端的。

monitor是数据库名字。更新了配置文件模板。
增加了monitor的数据库连接。

**Comment by flywithbug** [comment]
> 刚刚接触，没找到mongo的monitor库文件，报了空指针异常

我把项目拆分了下，https://github.com/flywithbug-vue-admin/go-eladmin 这里是后端的。

monitor是数据库名字。更新了配置文件模板。
增加了monitor的数据库连接。

**Comment by flywithbug** [comment]
> 刚刚接触，没找到mongo的monitor库文件，报了空指针异常

`
"db_config":{
    "url": "127.0.0.1:27017",
    "db_name": "doc_manager",
    "force_sync":true
  },
  "monitor_db_config":{
    "url": "127.0.0.1:27017",
    "db_name": "monitor",
    "force_sync":true
  },
`
